language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_ed896ba96142_key -iv $encrypted_ed896ba96142_iv
  -in rys_rsa.enc -out rys_rsa -d
- mv rys_rsa ~/.ssh -f  
- chmod 600 ~/.ssh/rys_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/rys_rsa
- cp .travis/ssh_config ~/.ssh/config
